### PR TITLE
Update mygdb.c

### PR DESCRIPTION
**Pull request by Nico01**
printf error :)

### CODE REVIEW

**Comment by javierhonduco** [comment]
Hi Nico,

What is that necessary? Is it because of some compiler flag that I haven't enabled?

Greetings,

**Comment by Nico01** [comment]
_printf_ don't accept  variables without a format specifier. You can "printf" a string (_printf("Hello")_) or use in this case _printf("%s", prompt_symbol);_.
What compiler version are you using? Mine (gcc 6.2.1) return: 

> mygdb.c:36:5: error: format not a string literal and no format arguments [-Werror=format-security]
>      printf(prompt_symbol);
>      ^~~~~~

**Comment by javierhonduco** [comment]
Oh, I'm using the same version, a bit weird I'm not getting the error! 😮 
Maybe you are on OSX which uses clang under the scenes?

Anyhow, you are right, it's a better approach to use "%s" if the string is provided externally, as it can be a security problem.
I've changed it to be a constant [here](https://github.com/javierhonduco/write-a-strace-and-gdb/commit/75c9d3aaabc2015a25b1c5952e6fb1fd707e497e).

Does it work for you?

Thanks! :)

**Comment by Nico01** [comment]
You forgotten to add "%s" in the printf func so i still get the error (because of "-Werror").
It's strange how with all the error flags you pass to the compiler you don't get the same error :/
Btw, i'm on linux (ubuntu).

**Comment by javierhonduco** [comment]
Sorry for the huge delay 😣 .

Thanks a lot for the patch :). I wanted to keep the variable around, and as you mentioned, we are not formatting any string, so I changed `printf` with `puts`.

**Pull request merged**
